// <auto-generated />
using ASM_hungnqph19112_CS4.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASM_hungnqph19112_CS4.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230805004712_auth")]
    partial class auth
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ASM_hungnqph19112_CS4.Data.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Orange"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Fresh Meat"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Vegetables"
                        },
                        new
                        {
                            Id = 4,
                            Title = "Fastfood"
                        });
                });

            modelBuilder.Entity("ASM_hungnqph19112_CS4.Data.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "details/mang-tay-1.jpg",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "details/mang-tay-2.jpg",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "details/mang-tay-3.jpg",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "details/mang-tay-4.jpg",
                            ProductId = 1
                        });
                });

            modelBuilder.Entity("ASM_hungnqph19112_CS4.Data.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Infomation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 3,
                            Description = "Măng tây được nuôi trồng tại Lâm Đồng và đóng gói theo những tiêu chuẩn nghiêm ngặt, bảo đảm các tiêu chuẩn xanh - sạch, chất lượng và an toàn với người dùng. Măng giòn, ngọt, hàm lượng dinh dưỡng cao nên thường được chế biên bằng hấp, luộc hoặc nướng để có thể giữ được độ tươi ngon.",
                            ImageUrl = "featured/mang-tay.jpg",
                            Infomation = "Giá trị dinh dưỡng của măng tây\r\nMăng tây là thực phẩm quý giá có chứa hàm lượng dinh dưỡng cao như: chất xơ, đạm, glucid, các vitamin K, C, A, pyridoxine (B6), riboflavin (B2), acid folic, canxi, sắt, kẽm…\r\nTrong 100g măng tây có 20.3 Kcal.\nTác dụng của măng tây đối với sức khỏe\r\nLàm đẹp da và ngăn ngừa lão hóa\r\nNgăn ngừa bệnh loãng xương\r\nNgăn ngừa bệnh ung thư\r\nTăng cường hệ miễn dịch\nCác món ăn ngon từ măng tây\r\nMăng tây thì bạn có thể chế biến thành nhiều món ăn khác nhau như: măng tây xào thịt bò, măng tây xào nấm, súp cá hồi phô mai măng tây, súp tôm măng tây,...\r\nCách bảo quản măng tây tươi ngon\r\nMăng tây nên được bảo quản trong ngăn mát tủ lạnh để giúp măng tây tươi ngon, giòn ngọt.",
                            Price = 27550m,
                            Title = "Măng tây Lâm Đồng 200g"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "None",
                            ImageUrl = "featured/feature-2.jpg",
                            Infomation = "No Infomation",
                            Price = 30000m,
                            Title = "Crab Pool Security"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "None",
                            ImageUrl = "featured/feature-3.jpg",
                            Infomation = "No Infomation",
                            Price = 30000m,
                            Title = "Crab Pool Security"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            Description = "None",
                            ImageUrl = "featured/feature-4.jpg",
                            Infomation = "No Infomation",
                            Price = 30000m,
                            Title = "Crab Pool Security"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "None",
                            ImageUrl = "featured/feature-5.jpg",
                            Infomation = "No Infomation",
                            Price = 30000m,
                            Title = "Crab Pool Security"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "None",
                            ImageUrl = "featured/feature-6.jpg",
                            Infomation = "No Infomation",
                            Price = 30000m,
                            Title = "Crab Pool Security"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Description = "None",
                            ImageUrl = "featured/feature-7.jpg",
                            Infomation = "No Infomation",
                            Price = 30000m,
                            Title = "Crab Pool Security"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Description = "None",
                            ImageUrl = "featured/feature-8.jpg",
                            Infomation = "No Infomation",
                            Price = 30000m,
                            Title = "Crab Pool Security"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Description = "None",
                            ImageUrl = "featured/feature-5.jpg",
                            Infomation = "No Infomation",
                            Price = 30000m,
                            Title = "Crab Pool Security"
                        });
                });

            modelBuilder.Entity("ASM_hungnqph19112_CS4.Data.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            RoleName = "Customer"
                        });
                });

            modelBuilder.Entity("ASM_hungnqph19112_CS4.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Account = "htttphpqh",
                            Password = "11234566",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            Account = "http1qh",
                            Password = "1123423",
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("ASM_hungnqph19112_CS4.Data.Image", b =>
                {
                    b.HasOne("ASM_hungnqph19112_CS4.Data.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ASM_hungnqph19112_CS4.Data.Product", b =>
                {
                    b.HasOne("ASM_hungnqph19112_CS4.Data.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ASM_hungnqph19112_CS4.Data.User", b =>
                {
                    b.HasOne("ASM_hungnqph19112_CS4.Data.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ASM_hungnqph19112_CS4.Data.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ASM_hungnqph19112_CS4.Data.Product", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("ASM_hungnqph19112_CS4.Data.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
